### ISSUE TITLE
Any document about the MVC?

### ISSUE THREAD

**Issue by zhouhao27** [petecoop/generator-express#147]
This is just the generator I want. But I don't quite understand the MVC works. Is there any document about this? For example:

How to add new controller, model, view? And how does the router work? Thanks.

Sorry for my possible stupid question because I'm still quite new at Express.

**Comment by petecoop** [comment]
I haven't provided any documentation on how to build once you've generated your project - mainly because it's built out of packages that already have good documentation and tutorials around them.

To add new controllers/models/views you can copy the examples I've given, but to have some more idea you'll need to look at the packages used, e.g. if using MySQL look at [Sequelize](http://docs.sequelizejs.com/en/latest/) which is the ORM used for the model.

To get an idea of how the router works, you'll need to look at the [Express Docs](http://expressjs.com/guide/routing.html).
