### ISSUE TITLE
Confusions with gulpfile.js?

### ISSUE THREAD

**Issue by THCloud** [petecoop/generator-express#173]
Hi,
I'm a new learner and trying to use this generator to do something. But I have some confusions with this gulpfile.js.

`gulp.task('develop', function() { `
`    livereload.listen();`
`    nodemon({`
`        ...`
`    }).on('readable', function() {`
`   this.stdout.on('data', function(chunk) {`
`    if(/^Express server listening on port/.test(chunk))`
`            livereload.changed(__dirname);`
`   });`
`  ... `  
`   });`
`});`

As you have started `livereload.listen()` at the beginning, and the console will print 'Express server listening on port ...' (app.js), why do you use `livereload.changed(__dirname)` ? Is there any benifits in it？

And another question...
As nodemon support files like jade, js, css,  Is there any worth with livereload ?? 

...How to type space in markdown.....

**Comment by petecoop** [comment]
`livereload.listen()` just starts the livereload server, which is used to send the files to your browser or trigger a refresh. `livereload.changed` is telling livereload to trigger a refresh of the browser.

Nodemon will listen for any changes to the files, and will restart the server but won't refresh the browser - which is why a change in Nodemon is then triggering a livereload change.

Hope that makes sense

**Comment by THCloud** [comment]
got it！thanks!
Well, maybe I have to review the apis of these modules...
